platform :ios, '10.3'
use_frameworks!

target 'Superdickery' do
  pod 'SwiftSoup'
  pod 'Gifu'
  pod 'Crashlytics'
  pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
end
